#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Data Loader Module

Loads ARFF and CSV files generated by pyloader.
"""

import pandas as pd
import numpy as np
import re
from pathlib import Path
from typing import Tuple, List, Optional


class ARFFLoader:
    """Load ARFF format files."""
    
    def __init__(self, file_path: str):
        self.file_path = file_path
        self.relation_name = None
        self.attributes = []
        self.attribute_types = {}
        self.data = None
        
    def load(self) -> pd.DataFrame:
        """Load ARFF file and return as pandas DataFrame."""
        with open(self.file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        data_start = None
        header_lines = []
        data_lines = []
        
        for i, line in enumerate(lines):
            line = line.strip()
            if line.startswith('@data'):
                data_start = i + 1
                break
            header_lines.append(line)
        
        if data_start is None:
            raise ValueError("Invalid ARFF file: no @data section found")
        
        data_lines = lines[data_start:]
        
        # Parse header
        self._parse_header(header_lines)
        
        # Parse data
        self._parse_data(data_lines)
        
        return self.data
    
    def _parse_header(self, lines: List[str]):
        """Parse ARFF header section."""
        for line in lines:
            line = line.strip()
            if not line or line.startswith('%'):
                continue
            
            if line.lower().startswith('@relation'):
                self.relation_name = line.split(None, 1)[1].strip().strip("'\"")
            
            elif line.lower().startswith('@attribute'):
                # Parse attribute definition
                match = re.match(r"@attribute\s+(\S+)\s+(.+)", line, re.IGNORECASE)
                if match:
                    attr_name = match.group(1).strip("'\"")
                    attr_type = match.group(2).strip()
                    self.attributes.append(attr_name)
                    self.attribute_types[attr_name] = attr_type
    
    def _parse_data(self, lines: List[str]):
        """Parse ARFF data section."""
        data = []
        for line in lines:
            line = line.strip()
            if not line or line.startswith('%'):
                continue
            
            # Split by comma, handling quoted strings
            values = self._split_values(line)
            data.append(values)
        
        self.data = pd.DataFrame(data, columns=self.attributes)
        
        # Convert numeric columns
        for col in self.attributes:
            if self.attribute_types.get(col) == 'numeric':
                self.data[col] = pd.to_numeric(self.data[col], errors='coerce')
            else:
                # Remove quotes from nominal values
                self.data[col] = self.data[col].str.strip("'\"")
    
    def _split_values(self, line: str) -> List[str]:
        """Split comma-separated values, handling quoted strings."""
        values = []
        current = []
        in_quotes = False
        quote_char = None
        
        for char in line:
            if char in "'\"":
                if not in_quotes:
                    in_quotes = True
                    quote_char = char
                elif char == quote_char:
                    in_quotes = False
                    quote_char = None
                else:
                    current.append(char)
            elif char == ',' and not in_quotes:
                values.append(''.join(current).strip())
                current = []
            else:
                current.append(char)
        
        values.append(''.join(current).strip())
        return values


class DataLoader:
    """Unified data loader for ARFF and CSV files."""
    
    def __init__(self, file_path: str, class_index: int = 0):
        self.file_path = Path(file_path)
        self.class_index = class_index
        self.data = None
        self.class_name = None
        
    def load(self) -> pd.DataFrame:
        """Load data file based on extension."""
        suffix = self.file_path.suffix.lower()
        
        if suffix == '.arff':
            loader = ARFFLoader(str(self.file_path))
            self.data = loader.load()
        elif suffix == '.csv':
            self.data = pd.read_csv(self.file_path)
        else:
            raise ValueError(f"Unsupported file format: {suffix}")
        
        # Set class name
        if self.class_index < len(self.data.columns):
            self.class_name = self.data.columns[self.class_index]
        
        return self.data
    
    def get_features_and_labels(self) -> Tuple[pd.DataFrame, pd.Series]:
        """Split data into features and labels."""
        if self.data is None:
            self.load()
        
        # Drop serial_number for features (used for tracking)
        feature_cols = [c for c in self.data.columns if c != 'serial_number']
        
        X = self.data[feature_cols].drop(columns=[self.class_name], errors='ignore')
        y = self.data[self.class_name] if self.class_name in self.data.columns else None
        
        return X, y
    
    def get_serial_numbers(self) -> Optional[pd.Series]:
        """Get serial numbers if available."""
        if 'serial_number' in self.data.columns:
            return self.data['serial_number']
        return None


def load_data(file_path: str, class_index: int = 0) -> pd.DataFrame:
    """Convenience function to load data."""
    loader = DataLoader(file_path, class_index)
    return loader.load()
